### ISSUE TITLE
 Program is using implicit definitions of functions getting

### ISSUE THREAD

**Issue by tigerfoot** [pramsey/libght#6]
Sorry a last one which should also be fixed ...

I: Program is using implicit definitions of functions getting
    pointers or implemented by macros. These functions need to use their
    correct prototypes to allow correct argument passing on e.g. x86_64 .
      - Implicit memory/string functions need #include <string.h>.
      - Implicit *printf functions need #include <stdio.h>.
      - Implicit *printf functions need #include <stdio.h>.
      - Implicit *read* functions need #include <unistd.h>.
      - Implicit *recv* functions need #include <sys/socket.h>.
 W: ght-tools implicit-pointer-decl /home/abuild/rpmbuild/BUILD/libght-0.1.0/src/ght_hash.c:171

**Comment by strk** [comment]
is this still a problem ? I didn't find any referenc eto printf/read/recv in that file...

**Comment by tigerfoot** [comment]
Nope I didn't see it anymore with all patches existing in master compared to 0.10 release
I'm closing it as workforme :-)
